openapi: 3.1.0
info:
  title: Bonbon Rewards API
  description: >-
    The Bonbon Rewards API allows you to create rewarded experiences for users
    on the Open Internet. Our offer database is made publicly avaialable here &
    us refreshed nightly: https://cdn.bonbon.tech/offers
  version: 1.0.0
  x-logo:
    url: https://portal.bonbon.tech/bonbon_logo.png
    backgroundColor: '#FFFFFF'
    altText: Bonbon logo
servers:
  - url: https://api.bonbon.tech/v1
    description: Production API v1 endpoint
  - url: https://sandbox.api.bonbon.tech/v1
    description: Sandbox API v1 endpoint
paths:
  /earn/otp:
    post:
      summary: /earn/otp
      description: >-
        Initiate a request for an earn token using the email OTP code flow.
        Dispatches an email with an OTP code the end user will later enter into
        your form to complete authentication & generate an earn token. The email
        will be branded per the clientId provided.
      parameters:
        - in: header
          name: x-bonbon-clientid
          schema:
            type: string
          examples:
            TestClientId:
              summary: The Client ID
              value: ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
      requestBody:
        description: The payload to begin an OTP code authentication.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: The user's email address
                  type: string
            examples:
              TestUser:
                summary: An OTP Example
                value:
                  email: test-user@bonbon.tech
      responses:
        '200':
          description: A JSON object with a success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A successful response
                  value:
                    message: Email sent to test-user@bonbon.tech
        '500':
          description: A JSON object with an error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: An error response
                  value:
                    message: >-
                      bad-user@bonbon.tech is not a valid mailbox. Please try
                      again with a valid email address.
  /earn/otp-token:
    post:
      summary: /earn/otp-token
      description: >-
        Exchange an email address / OTP code pair for an earn token. To be
        called after a successful call to `/earn/otp`, this method will return
        an earn token if the email and OTP code provided match expectations.
      parameters:
        - in: header
          name: x-bonbon-clientid
          schema:
            type: string
          examples:
            TestClientId:
              summary: The Client ID
              value: ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
      requestBody:
        description: The payload to exchange an email / OTP code pair for an earn token
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: The user's email address
                  type: string
                otp:
                  description: The OTP code for the given email address
                  type: string
                reward:
                  description: The ID of the reward from
                  type: string
                preferences:
                  description: >-
                    An object set of key/value pairs representing the user's
                    preferences must at least include the keys pAds and
                    newsletter with boolean values representing the user's
                    personalized ads and newsletter preferences, respectively.
                  type: object
                lastLoginUrl:
                  description: The URL where the user is logging in from
                  type: string
                bonbons:
                  description: The number of Bonbons to reward the user for logging in
                  type: integer
            examples:
              TestUser:
                summary: An otp-token example
                value:
                  email: test-user@bonbon.tech
                  otp: '123456'
                  reward: airpods_v1
                  preferences:
                    pAds: true
                    newsletter: true
                  lastLoginUrl: https://bonbon.tech
                  bonbons: 10
      responses:
        '200':
          description: A JSON object with the earn token
          content:
            application/json:
              schema:
                type: object
                properties:
                  earnToken:
                    type: string
                  signUp:
                    type: boolean
              examples:
                Success:
                  summary: A successful otp-token response
                  value:
                    earnToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
                    signUp: true
        '500':
          description: A JSON object with an error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: An error message
                  value:
                    message: Invalid email/otp combination. Please try again.
  /earn/oidc-token:
    post:
      summary: /earn/oidc-token
      description: >-
        Exchange an OIDC ID Token for an earn token. Used to perform an
        immediate exchange of an OIDC ID Token for an earn token. Ensure your
        JWKS is configured for your client ID to use this method.
      parameters:
        - in: header
          name: x-bonbon-clientid
          schema:
            type: string
          examples:
            TestClientId:
              summary: The Client ID
              value: ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
      requestBody:
        description: The payload to exchange an OIDC token for an earn token
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  description: The user's OIDC ID token.
                  type: string
                provider:
                  description: One of googlegsi, openpass, bonbonsso.
                  type: string
                reward:
                  description: The ID of a reward from our reward catalog.
                  type: string
                preferences:
                  description: An flat object of key/value pairs of preferences.
                  type: string
                lastLoginUrl:
                  description: The URL where the user is signing in.
                  type: string
                bonbons:
                  description: The number of Bonbons to reward the user for signing in.
                  type: integer
            examples:
              TestToken:
                summary: An oidc-token example
                value:
                  token: >-
                    eyJhbGciOiJSUzI1NiIsImtpZCI6Imkwd25uIn0.eyJzdWIiOiJqb2UiLCJhdWQiOiJpbV9vaWNfY2xpZW50IiwianRpIjoidWY5MFNLNHdzY0ZoY3RVVDZEdHZiMiIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTAzMSIsImlhdCI6MTM5NDA2MDg1MywiZXhwIjoxMzk0MDYxMTUzLCJub25jZSI6ImU5NTdmZmJhLTlhNzgtNGVhOS04ZWNhLWFlOGM0ZWY5Yzg1NiIsImF0X2hhc2giOiJ3Zmd2bUU5VnhqQXVkc2w5bGM2VHFBIn0
                  provider: bonbonsso
                  reward: airpods_v1
                  preferences:
                    pAds: true
                    newsletter: true
                  lastLoginUrl: https://bonbon.tech
                  bonbons: 10
      responses:
        '200':
          description: A JSON object with the earn token
          content:
            application/json:
              schema:
                type: object
                properties:
                  earnToken:
                    description: The user's earn token
                    type: string
              examples:
                Success:
                  summary: A successful otp-token response
                  value:
                    earnToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
                    signUp: true
        '500':
          description: A JSON object with an error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: An error message
                  value:
                    message: Invalid ID token.
  /earn:
    post:
      summary: /earn
      description: >-
        Called to log an earn action and credit the user associated with the
        earn token. Credits a user for a site activity.
      parameters:
        - in: header
          name: x-bonbon-clientid
          schema:
            type: string
          examples:
            TestClientId:
              summary: The Client ID
              value: ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
        - in: header
          name: Authorization
          schema:
            type: string
          examples:
            TestClientId:
              summary: The earn bearer token
              value: >-
                Bearer
                eyJhbGciOiJSUzI1NiIsImtpZCI6Imkwd25uIn0.eyJzdWIiOiJqb2UiLCJhdWQiOiJpbV9vaWNfY2xpZW50IiwianRpIjoidWY5MFNLNHdzY0ZoY3RVVDZEdHZiMiIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTAzMSIsImlhdCI6MTM5NDA2MDg1MywiZXhwIjoxMzk0MDYxMTUzLCJub25jZSI6ImU5NTdmZmJhLTlhNzgtNGVhOS04ZWNhLWFlOGM0ZWY5Yzg1NiIsImF0X2hhc2giOiJ3Zmd2bUU5VnhqQXVkc2w5bGM2VHFBIn0
      responses:
        '200':
          description: An empty string response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A successful earn response
                  value:
                    message: ok
        '429':
          description: A JSON object with an rate limit error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A error earn response
                  value:
                    message: User over rate limit for ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
        '500':
          description: A JSON object with an error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A error earn response
                  value:
                    message: >-
                      There was an error logging the earn activity. Please try
                      again.
  /user:
    get:
      summary: /user
      description: >-
        Called to fetch how many bonbons the user has accumulated and the latest
        reward they've expressed interest in winning.
      parameters:
        - in: header
          name: x-bonbon-clientid
          schema:
            type: string
          examples:
            TestClientId:
              summary: The Client ID
              value: ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
        - in: header
          name: Authorization
          schema:
            type: string
          examples:
            TestClientId:
              summary: The earn bearer token
              value: >-
                Bearer
                eyJhbGciOiJSUzI1NiIsImtpZCI6Imkwd25uIn0.eyJzdWIiOiJqb2UiLCJhdWQiOiJpbV9vaWNfY2xpZW50IiwianRpIjoidWY5MFNLNHdzY0ZoY3RVVDZEdHZiMiIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTAzMSIsImlhdCI6MTM5NDA2MDg1MywiZXhwIjoxMzk0MDYxMTUzLCJub25jZSI6ImU5NTdmZmJhLTlhNzgtNGVhOS04ZWNhLWFlOGM0ZWY5Yzg1NiIsImF0X2hhc2giOiJ3Zmd2bUU5VnhqQXVkc2w5bGM2VHFBIn0
      responses:
        '200':
          description: An empty string response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bonbons:
                    summary: >-
                      The number of Bonbons (entries to win) the user has
                      accumulated
                    type: integer
                  reward:
                    summary: >-
                      The ID of the latest reward the user has expressed
                      interest in winning.
                    type: string
              examples:
                Success:
                  summary: A successful earn response
                  value:
                    auth:
                      hem: XZDvQK/efPV1ssioCcAL3IjwJJYTsJFfeYbPKej9X2o=
                      uid2:
                        advertising_token: xxx
                        identity_expires: 1713474456684
                        refresh_expires: 1715807256684
                        refresh_from: 1713218856684
                        refresh_response_key: yyy
                        refresh_token: zzz
                    user_id: email|64641ae9fcc2eef15f95a412
                    user_metadata:
                      bonbons: 114
                      reward: airpods_v1
                      first_name: true
                      last_name: true
                      gender: false
                      postal: true
        '429':
          description: A JSON object with an rate limit error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A error earn response
                  value:
                    message: User over rate limit for ZcE2tPCuUMvRAkFiDkHyKQ1k4zR3kmda
        '500':
          description: A JSON object with an error message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Success:
                  summary: A error earn response
                  value:
                    message: >-
                      There was an error logging the earn activity. Please try
                      again.
components: {}
